# Globals
name: Forecast              # Used as the chart title.
description: "Plan A"       # Added to the title.
mode: monthly               # 'monthly' or 'yearly'

# Accounts
account:
  - name: default           # There must be at least one 'default' account.
    initial_balance: 1000   # Meaning, $1,000
    annual_return: 1.025    # Meaning, 1.025%
  - name: investment
    initial_balance: 10000
    annual_return: 8

# Incomes
income:
  - name: career            # Use any names you like.
    amount: 4500            # Your earnings (monthly or yearly).
    allocations:
      investment: 15        # Allocate 15% to the 'investment' account.
    dates:
      start: 01-2015        # Start on a given month (MM-YYYY) or year (YYYY).
      end: 01-2025          # End on a given month (MM-YYYY) or year (YYYY).
  - name: hustle
    amount: 250
    fluctuate: 25           # Randomize the amount between 75% to 125%.

# Expenses
expense:
  - name: household
    amount: 3500            # Your expense (monthly or yearly).
    fluctuate: 40           # Randomize the amount between 60% to 140%.
